### ISSUE TITLE
请问下这行代码的做用是？

### ISSUE THREAD

**Issue by YuanjianZhang** [leslievan/semi-utils#13]
缩放后的图片高度与背景图高度相减，不是一定会等于0吗?

https://github.com/leslievan/semi-utils/blob/1364d8021ffc4bd85c6d2e1ed19c0ee6c72aa7c8/image_processor.py#LL128C9-L128C9

**Comment by leslievan** [comment]
对，这里我没注意到，原本的设想是不缩放直接粘贴到上下居中的位置，已修改

**Comment by YuanjianZhang** [comment]
ok，没接触过python，看代码感觉有点怪怪的，所以问一下
