### ISSUE TITLE
能否增加保持宽高比的功能

### ISSUE THREAD

**Issue by lzzh** [leslievan/semi-utils#27]
能否添加自定义选项：保持相片的宽高比，这样在相片打印的时候可以免除二次裁切的动作。
如果还能增加自定义水印高度，那就更好了。

**Comment by leslievan** [comment]
指的是通过增加左右两侧的白边来保持原有比例，还是通过使用内边框遮挡原有内容来保持原有比例？

**Comment by lzzh** [comment]
感谢回复，两侧白边在打印的过程中可以通过缩放实现，所以不需要这样更改。
通过第二种方式实现原来比例应该可以的。
