### ISSUE TITLE
源码和压缩包都报这个错

### ISSUE THREAD

**Issue by Jingup** [leslievan/semi-utils#32]
<img width="639" alt="Snipaste_2023-04-20_11-33-10" src="https://user-images.githubusercontent.com/36259596/233251781-6c599397-e9c2-4067-9bc6-4cfd4dc949f0.png">

**Comment by leslievan** [comment]
字符串转 int 没加异常处理，下个版本我修一下

**Comment by Jingup** [comment]
<img width="521" alt="Snipaste_2023-04-20_14-23-51" src="https://user-images.githubusercontent.com/36259596/233276334-dd576e7e-f69f-4581-a96e-9a2287a5c592.png">
新的错误

**Comment by leslievan** [comment]
已尝试修复

**Comment by Jingup** [comment]
![image](https://user-images.githubusercontent.com/36259596/233297828-16cd7df1-fdad-432f-8d03-dd313c859f2f.png)
还是有问题，等你新版本吧

**Comment by leslievan** [comment]
可以发张原图我本地测试一下

**Comment by Jingup** [comment]
![20230418015428](https://user-images.githubusercontent.com/36259596/233300961-cc02ad0b-40c5-491f-b862-59e195f1922f.jpg)
图片大小 5.56MB

**Comment by Jingup** [comment]
可以了，感谢
