### ISSUE TITLE
拍摄日期识别不准确

### ISSUE THREAD

**Issue by xuejiannanyan** [leslievan/semi-utils#45]
![image](https://user-images.githubusercontent.com/121648673/235474030-404f0b44-17c9-4409-aed5-a50f5540307b.png)
拍摄日期前面的年月日不能正确识别，后面的小时分钟可以正确识别

**Comment by xuejiannanyan** [comment]
系统：Windows10
软件版本：v1.5.5
估计是***新增配置项：拍摄日期(eg. 2023-01-01)，与拍摄时间(eg. 2023-01-01 00:00)区分开**   的BUG

**Comment by xuejiannanyan** [comment]
软件版本v1.4.16识别正常

**Comment by leslievan** [comment]
可以给张原图我本地测试一下问题在哪里
