### ISSUE TITLE
v15.5&build1510 存在无法输出文件的情况

### ISSUE THREAD

**Issue by wrockwu** [leslievan/semi-utils#51]
两个版本均用默认配置测试。
发现input存放8.11MB的文件可以输出，存放9.25MB和13.2MB的文件无法输出并导致闪退。

input文件过大可能导致程序奔溃？

**Comment by CHCDST-SY** [comment]
3.41MB的图片也无法输出，exe程序按下回车后就闪退。

**Comment by leslievan** [comment]
可以用刚刚发的 1512 试试，1510 里循环写错了，任何一张图片无法处理都会导致闪退
