### ISSUE TITLE
加了边框之后图片颜色变浅

### ISSUE THREAD

**Issue by CHCDST-SY** [leslievan/semi-utils#52]
运行软件加了边框之后，图像颜色变淡变浅，是我设置有问题吗？

**Comment by leslievan** [comment]
导出图片的颜色空间需要选择 sRGB，用 Adobe RGB 或 DCI-P3 都会出现颜色变浅的问题

**Comment by CHCDST-SY** [comment]
> 导出图片的颜色空间需要选择 sRGB，用 Adobe RGB 或 DCI-P3 都会出现颜色变浅的问题

好的，明白了，感谢！
