### ISSUE TITLE
1512版本无法正确读取ps降噪处理后的图片信息

### ISSUE THREAD

**Issue by CHCDST-SY** [leslievan/semi-utils#53]
经过ps2023 camera raw 降噪处理后导出的sRGB格式图片，程序无法读取出其相机参数信息。
降噪处理前的图片可以正确读取。经查看图片详细信息，降噪前后的两张图片详细信息没有差别。

**Comment by leslievan** [comment]
可以提供一些样张我测试下嘛？我在 macOS 上用尼康的 nef 通过 Camera Raw 的”增强-另存为 jpeg“输出是ok的，需要看下怎么复现问题

**Comment by CHCDST-SY** [comment]
![DSC_0089-已增强-NR230528](https://github.com/leslievan/semi-utils/assets/46321100/4e186198-b43e-4248-a119-63b9b658ccf6)
![DSC_0089230529](https://github.com/leslievan/semi-utils/assets/46321100/eaa01d23-158f-448d-9a7c-8a4e3ea7f1af)


> 可以提供一些样张我测试下嘛？我在 macOS 上用尼康的 nef 通过 Camera Raw 的”增强-另存为 jpeg“输出是ok的，需要看下怎么复现问题

以上两张图片，已增强那张是经ps降噪处理后的图，我的系统是win11.

**Comment by CHCDST-SY** [comment]
> 可以提供一些样张我测试下嘛？我在 macOS 上用尼康的 nef 通过 Camera Raw 的”增强-另存为 jpeg“输出是ok的，需要看下怎么复现问题

或者您留个邮箱给我，我直接原图发您邮箱，不知道git这边上传下载会不会对图片进行二次编解码。

**Comment by leslievan** [comment]
可以看到的，我复现了问题，还没定位出是什么导致的

**Comment by leslievan** [comment]
#54 已修复
