### ISSUE TITLE
LR执行降噪导出的照片，无法获取相机信息

### ISSUE THREAD

**Issue by yushuishu** [leslievan/semi-utils#61]
正常照片的元数据，如下：
![image](https://github.com/leslievan/semi-utils/assets/50919172/07606b8e-5e5b-44fe-b73c-89fb3f8e44aa)

LR执行降噪生成DNG文件，再导出png文件之后，使用程序添加水印，检测不到照片，该照片元数据如下（没有EXIF）：
![image](https://github.com/leslievan/semi-utils/assets/50919172/60dcb0d8-5d12-4345-926b-c3423bada590)

在获取不到exif中的信息时，能否增加尝试获取xmp中的照相机信息？

**Comment by yushuishu** [comment]
看了源码，没有获取png文件
![image](https://github.com/leslievan/semi-utils/assets/50919172/8416af73-7469-4aa7-8ae0-f4f047927969)

**Comment by leslievan** [comment]
暂时没有处理 png 格式的图片，理论上程序是可以处理 png 图片的，但我没有测试过
