### ISSUE TITLE
python 源码执行，水印信息没有生成

### ISSUE THREAD

**Issue by qianchen9527** [leslievan/semi-utils#71]

**Comment by ShaKing-L** [comment]
同问，信息都为空，且时间为当前时间。
直接运行打包文件.exe能正常使用

**Comment by leslievan** [comment]
源码运行前要先执行下安装脚本，install.sh

**Comment by leslievan** [comment]
可能是 exiftools 没下载成功

**Comment by ShaKing-L** [comment]
<img width="812" alt="2023-11-22_192227" src="https://github.com/leslievan/semi-utils/assets/61108609/a5ac4a1c-857c-41c6-b10f-287e9af3bf41">
运行了install.sh，还是不行，图上是error.log的信息

**Comment by qianchen9527** [comment]
exiftools  下载成功后还是无法生成水印
![image](https://github.com/leslievan/semi-utils/assets/53032788/287ccfea-a7e6-44f1-8f2c-c8da5f95978e)
![image](https://github.com/leslievan/semi-utils/assets/53032788/dd0fdd9d-27ee-40b8-985e-38cd749467c7)

**Comment by qianchen9527** [comment]
![image](https://github.com/leslievan/semi-utils/assets/53032788/9c94eb8e-fde1-4d81-af9a-3be1ea449db7)

**Comment by qianchen9527** [comment]
![image](https://github.com/leslievan/semi-utils/assets/53032788/b43b9b66-90b1-4d0f-846d-457a3044f3bf)
看起来是你的运行配置里面还是用的exe的文件

**Comment by ShaKing-L** [comment]
### 已解决
可拷贝打好包的exiftool文件夹下的exiftool.exe到代码exiftool文件夹。
或者去 https://exiftool.org 下载.zip文件，同时去代码中修改 utils.py文件中 EXIFTOOL_PATH = Path('./exiftool/exiftool(-k).exe')
<img width="369" alt="2023-11-23_085219" src="https://github.com/leslievan/semi-utils/assets/61108609/c040e7a1-604b-417f-b134-11081e336d99">
windows环境下应运行install.ps1，但当前此脚本中下载的是.tar.gz文件，把脚本中的.tar.gz改为.zip且去修改如上代码。
但偶有报错，推荐手动下载。
