### ISSUE TITLE
一个小建议，可以加入一个自定义选择输入输出文件夹的功能

### ISSUE THREAD

**Issue by GoooForward** [leslievan/semi-utils#75]
原图一般都比较大，每次使用都要先拷贝进input，然后又从output拷贝出来，用起来比较麻烦。可以加入一个自定义选择输入输出文件夹的功能，或者给个可以更改的配置项也可以

**Comment by leslievan** [comment]
这个配置在 config.yaml 里面有，input 和 output 可以指定输入输出路径，但如果没有备份的话，建议谨慎操作，如果 input 和 output 指定为同一个目录可能会导致文件被覆盖
