### ISSUE TITLE
能否增加一个显示地理位置信息？

### ISSUE THREAD

**Issue by Rikkalxn** [leslievan/semi-utils#78]
可以考虑增加一个显示地理位置吗？经纬度格式的这种。

**Comment by leslievan** [comment]
已经加上了，照片里面有gps信息的话可以显示

**Comment by LucianXu** [comment]
<img width="372" height="77" alt="Image" src="https://github.com/user-attachments/assets/64f211be-8eb2-4590-8151-c1c38358ebdb" />
只显示经纬度是对的吗?
